name: Pruebas Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Ejecutar Pruebas Go
    runs-on: ubuntu-latest

    steps:
    - name: Obtener código
      uses: actions/checkout@v4

    - name: Configurar Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        check-latest: true

    - name: Obtener dependencias
      run: go mod download

    - name: Ejecutar pruebas
      run: go test -v ./...
